import {
  MdAccountBalance, MdAccountCircle, MdArrowForward, MdAutoStories, MdBiotech, MdBuild,
  MdCalculate, MdCall, MdCampaign, MdCheckCircle, MdClose, MdCloudDownload, MdCode, MdCoPresent,
  MdDevices, MdDiversity1, MdDraw, MdError, MdEvent, MdExpandMore, MdFactCheck, MdFavorite, MdFlag,
  MdFormatListBulleted, MdForum, MdFunctions, MdGavel, MdGroups, MdHandyman, MdHandshake, MdHistory,
  MdHistoryEdu, MdHome, MdHowToReg, MdInfo, MdScience, MdLightbulb, MdLiveTv, MdLocationOn, MdLockReset,
  MdLogin, MdMail, MdMarkEmailRead, MdMenu, MdMenuBook, MdMonitor, MdMonitorHeart, MdAnalytics,
  MdNotifications, MdNotificationsActive, MdOpenInNew, MdPayments, MdPersonAdd, MdPhoneAndroid,
  MdPictureAsPdf, MdPlayArrow, MdPlayCircle, MdPolicy, MdPsychology, MdPublic, MdQrCode2, MdQuiz,
  MdSchool, MdSend, MdShare, MdShield, MdSmartDisplay, MdSms, MdSpeed, MdStars, MdSupportAgent,
  MdTrackChanges, MdTranslate, MdTrendingUp, MdUpdate, MdUploadFile, MdVerified, MdVideocam,
  MdVisibility, MdWork, MdWorkspacePremium,
  MdOutlineAccountBalance, MdOutlineAccountCircle, MdOutlineArrowForward, MdOutlineAutoStories,
  MdOutlineBiotech, MdOutlineBuild, MdOutlineCalculate, MdOutlineCall, MdOutlineCampaign,
  MdOutlineCheckCircle, MdOutlineClose, MdOutlineCloudDownload, MdOutlineCode, MdOutlineCoPresent,
  MdOutlineDevices, MdOutlineDiversity1, MdOutlineDraw, MdOutlineError, MdOutlineEvent,
  MdOutlineExpandMore, MdOutlineFactCheck, MdOutlineFavorite, MdOutlineFlag, MdOutlineFormatListBulleted,
  MdOutlineForum, MdOutlineFunctions, MdOutlineGavel, MdOutlineGroups, MdOutlineHandyman,
  MdOutlineHandshake, MdOutlineHistory, MdOutlineHistoryEdu, MdOutlineHome, MdOutlineHowToReg,
  MdOutlineInfo, MdOutlineScience, MdOutlineLightbulb, MdOutlineLiveTv, MdOutlineLocationOn,
  MdOutlineLockReset, MdOutlineLogin, MdOutlineMail, MdOutlineMarkEmailRead, MdOutlineMenu,
  MdOutlineMenuBook, MdOutlineMonitor, MdOutlineMonitorHeart, MdOutlineAnalytics, MdOutlineNotifications,
  MdOutlineNotificationsActive, MdOutlineOpenInNew, MdOutlinePayments, MdOutlinePersonAdd,
  MdOutlinePhoneAndroid, MdOutlinePictureAsPdf, MdOutlinePlayArrow, MdOutlinePlayCircle,
  MdOutlinePolicy, MdOutlinePsychology, MdOutlinePublic, MdOutlineQrCode2, MdOutlineQuiz,
  MdOutlineSchool, MdOutlineSend, MdOutlineShare, MdOutlineShield, MdOutlineSmartDisplay, MdOutlineSms,
  MdOutlineSpeed, MdOutlineStars, MdOutlineSupportAgent, MdOutlineTrackChanges, MdOutlineTranslate,
  MdOutlineTrendingUp, MdOutlineUpdate, MdOutlineUploadFile, MdOutlineVerified, MdOutlineVideocam,
  MdOutlineVisibility, MdOutlineWork, MdOutlineWorkspacePremium,
} from 'react-icons/md'

const ICONS = {
  account_balance: [MdAccountBalance, MdOutlineAccountBalance],
  account_circle: [MdAccountCircle, MdOutlineAccountCircle],
  arrow_forward: [MdArrowForward, MdOutlineArrowForward],
  auto_stories: [MdAutoStories, MdOutlineAutoStories],
  biotech: [MdBiotech, MdOutlineBiotech],
  build: [MdBuild, MdOutlineBuild],
  calculate: [MdCalculate, MdOutlineCalculate],
  call: [MdCall, MdOutlineCall],
  campaign: [MdCampaign, MdOutlineCampaign],
  check_circle: [MdCheckCircle, MdOutlineCheckCircle],
  close: [MdClose, MdOutlineClose],
  cloud_download: [MdCloudDownload, MdOutlineCloudDownload],
  code: [MdCode, MdOutlineCode],
  co_present: [MdCoPresent, MdOutlineCoPresent],
  devices: [MdDevices, MdOutlineDevices],
  diversity_1: [MdDiversity1, MdOutlineDiversity1],
  draw: [MdDraw, MdOutlineDraw],
  error: [MdError, MdOutlineError],
  event: [MdEvent, MdOutlineEvent],
  expand_more: [MdExpandMore, MdOutlineExpandMore],
  fact_check: [MdFactCheck, MdOutlineFactCheck],
  favorite: [MdFavorite, MdOutlineFavorite],
  flag: [MdFlag, MdOutlineFlag],
  format_list_bulleted: [MdFormatListBulleted, MdOutlineFormatListBulleted],
  forum: [MdForum, MdOutlineForum],
  functions: [MdFunctions, MdOutlineFunctions],
  gavel: [MdGavel, MdOutlineGavel],
  groups: [MdGroups, MdOutlineGroups],
  handyman: [MdHandyman, MdOutlineHandyman],
  handshake: [MdHandshake, MdOutlineHandshake],
  history: [MdHistory, MdOutlineHistory],
  history_edu: [MdHistoryEdu, MdOutlineHistoryEdu],
  home: [MdHome, MdOutlineHome],
  how_to_reg: [MdHowToReg, MdOutlineHowToReg],
  info: [MdInfo, MdOutlineInfo],
  labs: [MdScience, MdOutlineScience],
  lightbulb: [MdLightbulb, MdOutlineLightbulb],
  live_tv: [MdLiveTv, MdOutlineLiveTv],
  location_on: [MdLocationOn, MdOutlineLocationOn],
  lock_reset: [MdLockReset, MdOutlineLockReset],
  login: [MdLogin, MdOutlineLogin],
  mail: [MdMail, MdOutlineMail],
  mark_email_read: [MdMarkEmailRead, MdOutlineMarkEmailRead],
  menu: [MdMenu, MdOutlineMenu],
  menu_book: [MdMenuBook, MdOutlineMenuBook],
  monitor: [MdMonitor, MdOutlineMonitor],
  monitor_heart: [MdMonitorHeart, MdOutlineMonitorHeart],
  monitoring: [MdAnalytics, MdOutlineAnalytics],
  notifications: [MdNotifications, MdOutlineNotifications],
  notifications_active: [MdNotificationsActive, MdOutlineNotificationsActive],
  open_in_new: [MdOpenInNew, MdOutlineOpenInNew],
  payments: [MdPayments, MdOutlinePayments],
  person_add: [MdPersonAdd, MdOutlinePersonAdd],
  phone_android: [MdPhoneAndroid, MdOutlinePhoneAndroid],
  picture_as_pdf: [MdPictureAsPdf, MdOutlinePictureAsPdf],
  play_arrow: [MdPlayArrow, MdOutlinePlayArrow],
  play_circle: [MdPlayCircle, MdOutlinePlayCircle],
  policy: [MdPolicy, MdOutlinePolicy],
  psychology: [MdPsychology, MdOutlinePsychology],
  public: [MdPublic, MdOutlinePublic],
  qr_code_2: [MdQrCode2, MdOutlineQrCode2],
  quiz: [MdQuiz, MdOutlineQuiz],
  school: [MdSchool, MdOutlineSchool],
  science: [MdScience, MdOutlineScience],
  send: [MdSend, MdOutlineSend],
  share: [MdShare, MdOutlineShare],
  shield: [MdShield, MdOutlineShield],
  smart_display: [MdSmartDisplay, MdOutlineSmartDisplay],
  sms: [MdSms, MdOutlineSms],
  speed: [MdSpeed, MdOutlineSpeed],
  stars: [MdStars, MdOutlineStars],
  support_agent: [MdSupportAgent, MdOutlineSupportAgent],
  target: [MdTrackChanges, MdOutlineTrackChanges],
  translate: [MdTranslate, MdOutlineTranslate],
  trending_up: [MdTrendingUp, MdOutlineTrendingUp],
  update: [MdUpdate, MdOutlineUpdate],
  upload_file: [MdUploadFile, MdOutlineUploadFile],
  verified: [MdVerified, MdOutlineVerified],
  videocam: [MdVideocam, MdOutlineVideocam],
  visibility: [MdVisibility, MdOutlineVisibility],
  work: [MdWork, MdOutlineWork],
  workspace_premium: [MdWorkspacePremium, MdOutlineWorkspacePremium],
}

const FALLBACK = [MdInfo, MdOutlineInfo]

export default function Icon({ name, fill = false, className = '' }) {
  const [Filled, Outline] = ICONS[name] || FALLBACK
  const Component = fill ? Filled : Outline
  return <Component aria-hidden="true" className={className} />
}
